"""added column code in group table

Revision ID: 0427b5e648b1
Revises: 58a67afb887e
Create Date: 2025-02-06 13:33:04.614131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0427b5e648b1'
down_revision: Union[str, None] = '58a67afb887e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('code', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_groups_code'), 'groups', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_code'), table_name='groups')
    op.drop_column('groups', 'code')
    # ### end Alembic commands ###
