"""add scheduled_date to rides

Revision ID: 0e46006d5998
Revises: 8fd349575130
Create Date: 2025-12-23 13:41:44.576828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e46006d5998'
down_revision: Union[str, None] = '8fd349575130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_checkpoints', sa.Column('address', sa.String(), nullable=True))
    op.add_column('rides', sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'scheduled_date')
    op.drop_column('ride_checkpoints', 'address')
    # ### end Alembic commands ###
