"""soft_delete_vehicles

Revision ID: 0f47d9f8bde9
Revises: 36f7d1999ca3
Create Date: 2026-01-18 13:38:33.866198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f47d9f8bde9'
down_revision: Union[str, None] = '36f7d1999ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ride_information', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_ride_information', 'is_deleted')
    # ### end Alembic commands ###
