"""added back distance_traveled_km

Revision ID: 186061fbde36
Revises: ee84f17b0612
Create Date: 2025-12-24 15:24:19.699708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186061fbde36'
down_revision: Union[str, None] = 'ee84f17b0612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('distance_traveled_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'distance_traveled_km')
    # ### end Alembic commands ###
