"""added column group own in Group and relationship in user and group table

Revision ID: 29ae788159bd
Revises: 0427b5e648b1
Create Date: 2025-02-06 14:06:49.768988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ae788159bd'
down_revision: Union[str, None] = '0427b5e648b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_groups_owner'), 'groups', ['owner'], unique=False)
    op.create_foreign_key(None, 'groups', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_owner'), table_name='groups')
    op.drop_column('groups', 'owner')
    # ### end Alembic commands ###
