"""add_is_deleted_to_ride_participants

Revision ID: 36f7d1999ca3
Revises: bf1ec929c237
Create Date: 2026-01-17 15:09:49.351895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f7d1999ca3'
down_revision: Union[str, None] = 'bf1ec929c237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default for existing rows
    op.add_column('ride_participants', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # Remove server default after column is added
    op.alter_column('ride_participants', 'is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_participants', 'is_deleted')
    # ### end Alembic commands ###
