"""added marked by and marked at

Revision ID: 449e3c8130be
Revises: 186061fbde36
Create Date: 2025-12-24 16:35:19.500560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449e3c8130be'
down_revision: Union[str, None] = '186061fbde36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('marked_by', sa.UUID(), nullable=True))
    op.add_column('attendance_records', sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'attendance_records', 'users', ['marked_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_column('attendance_records', 'marked_at')
    op.drop_column('attendance_records', 'marked_by')
    # ### end Alembic commands ###
