"""added is_deleted field in organisations

Revision ID: 4d729154c447
Revises: d8c442190f4d
Create Date: 2025-12-22 22:07:12.828371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d729154c447'
down_revision: Union[str, None] = 'd8c442190f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
