"""added columm role as enum in GroupMembership

Revision ID: 509ad1cd85f4
Revises: 29ae788159bd
Create Date: 2025-02-07 14:34:42.022997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM



# revision identifiers, used by Alembic.
revision: str = '509ad1cd85f4'
down_revision: Union[str, None] = '29ae788159bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


group_enum = ENUM('ADMIN', 'MEMBER', name='groupusertype', create_type=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_memberships', 'role',
               existing_type=sa.String(),
               type_=group_enum,
               postgresql_using="role::text::groupusertype",
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'groups',
        'role',
        existing_type=group_enum,
        type_=sa.String()
    )
    group_enum.drop(op.get_bind())
    # ### end Alembic commands ###
