"""added user settings table

Revision ID: 58a67afb887e
Revises: 1bfd6bc5849b
Create Date: 2025-02-04 18:04:31.870221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a67afb887e'
down_revision: Union[str, None] = '1bfd6bc5849b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_setting', sa.Column('max_group_creation', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_setting', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_setting', type_='foreignkey')
    op.drop_column('user_setting', 'max_group_creation')
    # ### end Alembic commands ###
