"""Updated Device Info table

Revision ID: 6462c5301cea
Revises: 05f627d45e56
Create Date: 2025-07-27 18:00:35.096128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6462c5301cea'
down_revision: Union[str, None] = '05f627d45e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_infos', sa.Column('is_current_device', sa.Boolean(), nullable=False))
    op.add_column('device_infos', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('device_infos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('unique_user_device', 'device_infos', ['user_id', 'device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_device', 'device_infos', type_='unique')
    op.drop_column('device_infos', 'updated_at')
    op.drop_column('device_infos', 'last_active_at')
    op.drop_column('device_infos', 'is_current_device')
    # ### end Alembic commands ###
