"""Created fresh migrations

Revision ID: 6d5c06b5b57d
Revises: 
Create Date: 2025-12-21 18:49:44.551904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5c06b5b57d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'NORMAL_USER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('device_infos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=150), nullable=True),
    sa.Column('device_model', sa.String(length=150), nullable=True),
    sa.Column('device_brand', sa.String(length=150), nullable=True),
    sa.Column('os_name', sa.String(length=150), nullable=True),
    sa.Column('os_version', sa.String(length=150), nullable=True),
    sa.Column('app_version', sa.String(length=150), nullable=True),
    sa.Column('screen_width', sa.String(length=150), nullable=True),
    sa.Column('screen_height', sa.String(length=150), nullable=True),
    sa.Column('timezone', sa.String(length=150), nullable=True),
    sa.Column('locale', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_current_device', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='unique_user_device')
    )
    op.create_index(op.f('ix_device_infos_app_version'), 'device_infos', ['app_version'], unique=False)
    op.create_index(op.f('ix_device_infos_device_brand'), 'device_infos', ['device_brand'], unique=False)
    op.create_index(op.f('ix_device_infos_device_id'), 'device_infos', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_infos_device_model'), 'device_infos', ['device_model'], unique=False)
    op.create_index(op.f('ix_device_infos_id'), 'device_infos', ['id'], unique=False)
    op.create_index(op.f('ix_device_infos_locale'), 'device_infos', ['locale'], unique=False)
    op.create_index(op.f('ix_device_infos_os_name'), 'device_infos', ['os_name'], unique=False)
    op.create_index(op.f('ix_device_infos_os_version'), 'device_infos', ['os_version'], unique=False)
    op.create_index(op.f('ix_device_infos_screen_height'), 'device_infos', ['screen_height'], unique=False)
    op.create_index(op.f('ix_device_infos_screen_width'), 'device_infos', ['screen_width'], unique=False)
    op.create_index(op.f('ix_device_infos_timezone'), 'device_infos', ['timezone'], unique=False)
    op.create_index(op.f('ix_device_infos_user_id'), 'device_infos', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('owner', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_code'), 'groups', ['code'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_owner'), 'groups', ['owner'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('FOUNDER', 'CO_FOUNDER', 'ADMIN', name='organizationrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='unique_organization_user_member')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', name='ridestatus'), nullable=False),
    sa.Column('max_riders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_index(op.f('ix_rides_organization_id'), 'rides', ['organization_id'], unique=False)
    op.create_table('user_ride_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_pillion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'license_plate', name='unique_user_license_plate')
    )
    op.create_index(op.f('ix_user_ride_information_id'), 'user_ride_information', ['id'], unique=False)
    op.create_index(op.f('ix_user_ride_information_user_id'), 'user_ride_information', ['user_id'], unique=False)
    op.create_table('user_setting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_group_creation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_id'), 'user_setting', ['id'], unique=False)
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.Enum('MEETUP', 'DESTINATION', 'DISBURSEMENT', name='checkpointtype'), nullable=False),
    sa.Column('reached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('distance_traveled_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'user_id', 'checkpoint_type', name='unique_ride_user_checkpoint_attendance')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_ride_id'), 'attendance_records', ['ride_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='groupusertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    op.create_table('group_user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('is_location_sharing_on', sa.Boolean(), nullable=False),
    sa.Column('location_sharing_mode', sa.String(), nullable=False),
    sa.Column('location_sharing_radius_meters', sa.Integer(), nullable=True),
    sa.Column('is_auto_play_audio', sa.Boolean(), nullable=False),
    sa.Column('is_notification_on', sa.Boolean(), nullable=False),
    sa.Column('is_push_notification_on', sa.Boolean(), nullable=False),
    sa.Column('is_online_status_visible', sa.Boolean(), nullable=False),
    sa.Column('is_last_seen_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='unique_user_group_settings')
    )
    op.create_index(op.f('ix_group_user_settings_group_id'), 'group_user_settings', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_user_settings_id'), 'group_user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_group_user_settings_user_id'), 'group_user_settings', ['user_id'], unique=False)
    op.create_table('ride_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MEETUP', 'DESTINATION', 'DISBURSEMENT', name='checkpointtype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_checkpoints_id'), 'ride_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_ride_checkpoints_ride_id'), 'ride_checkpoints', ['ride_id'], unique=False)
    op.create_table('ride_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_info_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('RIDER', 'LEAD', 'MARSHAL', 'SWEEP', name='participantrole'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_info_id'], ['user_ride_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'user_id', name='unique_ride_participant')
    )
    op.create_index(op.f('ix_ride_participants_id'), 'ride_participants', ['id'], unique=False)
    op.create_index(op.f('ix_ride_participants_ride_id'), 'ride_participants', ['ride_id'], unique=False)
    op.create_index(op.f('ix_ride_participants_user_id'), 'ride_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_ride_participants_vehicle_info_id'), 'ride_participants', ['vehicle_info_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_participants_vehicle_info_id'), table_name='ride_participants')
    op.drop_index(op.f('ix_ride_participants_user_id'), table_name='ride_participants')
    op.drop_index(op.f('ix_ride_participants_ride_id'), table_name='ride_participants')
    op.drop_index(op.f('ix_ride_participants_id'), table_name='ride_participants')
    op.drop_table('ride_participants')
    op.drop_index(op.f('ix_ride_checkpoints_ride_id'), table_name='ride_checkpoints')
    op.drop_index(op.f('ix_ride_checkpoints_id'), table_name='ride_checkpoints')
    op.drop_table('ride_checkpoints')
    op.drop_index(op.f('ix_group_user_settings_user_id'), table_name='group_user_settings')
    op.drop_index(op.f('ix_group_user_settings_id'), table_name='group_user_settings')
    op.drop_index(op.f('ix_group_user_settings_group_id'), table_name='group_user_settings')
    op.drop_table('group_user_settings')
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_ride_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_index(op.f('ix_user_setting_id'), table_name='user_setting')
    op.drop_table('user_setting')
    op.drop_index(op.f('ix_user_ride_information_user_id'), table_name='user_ride_information')
    op.drop_index(op.f('ix_user_ride_information_id'), table_name='user_ride_information')
    op.drop_table('user_ride_information')
    op.drop_index(op.f('ix_rides_organization_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_groups_owner'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_code'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_device_infos_user_id'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_timezone'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_screen_width'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_screen_height'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_os_version'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_os_name'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_locale'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_id'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_device_model'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_device_id'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_device_brand'), table_name='device_infos')
    op.drop_index(op.f('ix_device_infos_app_version'), table_name='device_infos')
    op.drop_table('device_infos')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
