"""add payment fields to rides and participants

Revision ID: 8fd349575130
Revises: 4d729154c447
Create Date: 2025-12-23 08:01:10.161639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd349575130'
down_revision: Union[str, None] = '4d729154c447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_participants', sa.Column('has_paid', sa.Boolean(), nullable=False))
    op.add_column('ride_participants', sa.Column('paid_amount', sa.Float(), nullable=False))
    op.add_column('ride_participants', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rides', sa.Column('requires_payment', sa.Boolean(), nullable=False))
    op.add_column('rides', sa.Column('amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'amount')
    op.drop_column('rides', 'requires_payment')
    op.drop_column('ride_participants', 'payment_date')
    op.drop_column('ride_participants', 'paid_amount')
    op.drop_column('ride_participants', 'has_paid')
    # ### end Alembic commands ###
