"""add ride type field in ride model

Revision ID: 91f73a1c74f3
Revises: 0e46006d5998
Create Date: 2025-12-23 15:17:42.835276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '91f73a1c74f3'
down_revision: Union[str, None] = '0e46006d5998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ride_type_enum = postgresql.ENUM('ONE_DAY', 'MULTI_DAY', 'QUICK_RIDE', name='ridetype')
    ride_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('rides',
                  sa.Column('ride_type',
                            sa.Enum('ONE_DAY', 'MULTI_DAY', 'QUICK_RIDE', name='ridetype'), nullable=False,
                            server_default='ONE_DAY'  # This fills existing rows with 'ONE_DAY'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'ride_type')
    # ### end Alembic commands ###
