"""make email nullable and is active false

Revision ID: 9e40612620cb
Revises: 555dab1b7dfb
Create Date: 2025-01-31 14:00:54.466891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e40612620cb'
down_revision: Union[str, None] = '555dab1b7dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    server_default=sa.text('false'),
                    existing_server_default=sa.text('false'))

    op.alter_column(
        'users',
        'email',
        existing_type=sa.String(),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
