"""add status and reason to attendance

Revision ID: a33d830007fb
Revises: 91f73a1c74f3
Create Date: 2025-12-24 14:44:33.465722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a33d830007fb'
down_revision: Union[str, None] = '91f73a1c74f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('attendance_records', sa.Column('reason', sa.String(length=200), nullable=True))
    op.alter_column('attendance_records', 'checkpoint_type',
               existing_type=postgresql.ENUM('MEETUP', 'DESTINATION', 'DISBURSEMENT', name='checkpointtype'),
               nullable=True)
    op.drop_column('attendance_records', 'distance_traveled_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('distance_traveled_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('attendance_records', 'checkpoint_type',
               existing_type=postgresql.ENUM('MEETUP', 'DESTINATION', 'DISBURSEMENT', name='checkpointtype'),
               nullable=False)
    op.drop_column('attendance_records', 'reason')
    op.drop_column('attendance_records', 'status')
    # ### end Alembic commands ###
