"""add_join_code_to_organization

Revision ID: aee8c86e6092
Revises: 4a0a54091670
Create Date: 2026-01-04 11:36:43.522275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee8c86e6092'
down_revision: Union[str, None] = '4a0a54091670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('join_code', sa.String(length=12), nullable=True))
    op.add_column('organizations', sa.Column('join_code_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_organizations_join_code'), 'organizations', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_join_code'), table_name='organizations')
    op.drop_column('organizations', 'join_code_created_at')
    op.drop_column('organizations', 'join_code')
    # ### end Alembic commands ###
