"""Added logo in Org table and name unique

Revision ID: b9e5294487ba
Revises: 6d5c06b5b57d
Create Date: 2025-12-22 12:30:36.375939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e5294487ba'
down_revision: Union[str, None] = '6d5c06b5b57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo', sa.String(), nullable=True))
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_column('organizations', 'logo')
    # ### end Alembic commands ###
