"""added is_deleted field in organisations

Revision ID: d8c442190f4d
Revises: 08155dc621d3
Create Date: 2025-12-22 22:02:28.122979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c442190f4d'
down_revision: Union[str, None] = '08155dc621d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_members', 'is_deleted')
    # ### end Alembic commands ###
